### ISSUE TITLE
PCNC 440

### ISSUE THREAD

**Issue by Z-K-O** [SCC-Makerspace/Task-Tracker-Backend#16]
```[tasklist]
### Tasks
- [x] VESA mount touch screens
- [x] Install spindle lights
- [ ] Set up coolant options
- [ ] Check way lubricator output
- [ ] https://github.com/SCC-Makerspace/Task-Tracker-Backend/issues/75
```
