### ISSUE TITLE
Safety and Clean up stations

### ISSUE THREAD

**Issue by hnhogan** [SCC-Makerspace/Task-Tracker-Backend#45]
```[tasklist]
### Tasks
- [ ] Wall-mounted places to keep broom, dustbin
- [ ] gloves, eye and ear protection
- [ ] fire extinguishers
- [ ] eye rinse emergency station
```
