### ISSUE TITLE
GitHub expense tracking

### ISSUE THREAD

**Issue by Z-K-O** [SCC-Makerspace/Task-Tracker-Backend#56]
```[tasklist]
### Tasks
- [x] Create Excel VBA database scraper
- [x] Deploy GitHub app for exporting data
- [ ] Integrate importer and exporter
- [ ] Process imported data
```
